
<html lang="en">
```{r message=FALSE, warning=FALSE, echo=FALSE}
library(tidyverse)
library(ggplot2)
library(ggmap)
library(RColorBrewer)
library(patchwork)
library(here)
```
<head>
</head>
<body>
<h2>Introduction</h2>
<p>This application was developed by graduate students at the <a href="https://oneill.indiana.edu">Paul H. O'Neill School of Public and Environmental Affairs</a> at Indiana University - Bloomington for the <a href="https://www.ampathkenya.org/">Academic Model Providing Access to Healthcare (AMPATH)</a> partnership. The intended purpose of this application is to provide a tool to visually compare the direct and opportunity costs of antiretroviral cooperative care models. This calculator was produced as part of a graduate capstone course in the fall semester of 2020. The data and calculations used to present these figures are sourced from a study overseen by Dr. Suzanne Goodrich and through capstone research.</p>
<br>
<br>
<p>For more information, contact us:</p>
<br>
<p>Capstone Communications Lead</p>
<p>William Mahoney: <a href="mailto:wmmahone@indiana.edu">wmmahone@indiana.edu</a></p>
<p>Supervising Professor</p>
<p>Dr. Diane Henshel: <a href="mailto:dhenshel@indiana.edu">dhenshel@indiana.edu</a></p>
</body>
</html>
